openapi: '3.0.2'
info:
  title: OpenAPI Foreduc
  version: '1.0'

paths:
  /login:
    x-exegesis-controller: user.controller
    post:
      summary: Вход в систему с генерацией токена
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              parameters:
                username:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
      responses:
        '200':
          description: Пользователь присутствует в системе, выдается токен
          content:
            application/json:
              schema:
                type: object
                parameters:
                  token:
                    type: string

  /sign:
    x-exegesis-controller: user.controller
    post:
      summary: Регистрация пользователя
      operationId: sign
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Пользователь успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users:
    x-exegesis-controller: user.controller
    get:
      security:
        - BearerAuth: []
      description: Отдает список юзеров
      operationId: getList
      parameters:
        - $ref: '#/components/parameters/TakeParam'
        - $ref: '#/components/parameters/SkipParam'
        - in: query
          name: department
          schema:
            type: string
      responses:
        '200':
          description: Список юзеров
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /users/{id}:
    x-exegesis-controller: user.controller
    get:
      security:
        - BearerAuth: []
      description: Отдает юзера
      operationId: getItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      responses:
        '200':
          description: Объект юзера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      security:
        - BearerAuth: []
      description: Модифицирует юзера и возвращает его
      operationId: updateItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      parameters:
        - $ref: '#/components/parameters/UidParam'
      responses:
        '200':
          description: Удаленный юзер
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      security:
        - BearerAuth: []
      description: Удаляет юзера и возвращает его
      operationId: deleteItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      responses:
        '200':
          description: Удаленный юзер
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /groups:
    x-exegesis-controller: group.controller
    post:
      security:
        - BearerAuth: []
      description: Создает новую группу
      operationId: createItem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Созданная группа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
    get:
      security:
        - BearerAuth: []
      description: Отдает список группы
      operationId: getList
      parameters:
        - $ref: '#/components/parameters/TakeParam'
        - $ref: '#/components/parameters/SkipParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'

  /groups/{id}:
    x-exegesis-controller: group.controller
    get:
      security:
        - BearerAuth: []
      description: Отдает группу
      operationId: getItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      responses:
        '200':
          description: Объект группы
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
    put:
      security:
        - BearerAuth: []
      description: Модифицирует группу и возвращает ее
      operationId: updateItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
      responses:
        '200':
          description: Модифицированная группа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
    delete:
      security:
        - BearerAuth: []
      description: Удаляет группу и возвращает ее
      operationId: deleteItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      responses:
        '200':
          description: Удаленная группа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'

  /specializations:
    x-exegesis-controller: specialization.controller
    post:
      security:
        - BearerAuth: []
      description: Создаёт новую специальность
      operationId: createItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Specialization'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Specialization'
    get:
      security:
        - BearerAuth: []
      description: Отдаёт список специальностей
      operationId: getList
      parameters:
        - $ref: '#/components/parameters/TakeParam'
        - $ref: '#/components/parameters/SkipParam'
      responses:
        '200':
          description: Список специальностей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Specialization'

  /specializations/{id}:
    x-exegesis-controller: specialization.controller
    get:
      security:
        - BearerAuth: []
      description: Отдаёт специализацию
      operationId: getItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      responses:
        '200':
          description: Объект специализации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Specialization'
    put:
      security:
        - BearerAuth: []
      description: Модифицирует специализацию
      operationId: updateItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Specialization'
      responses:
        '200':
          description: Модфицированная специализация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Specialization'
    delete:
      security:
        - BearerAuth: []
      description: Удаляет группу и возвращает ее
      operationId: deleteItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      responses:
        '200':
          description: Удаленная группа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Specialization'

  /documents:
    x-exegesis-controller: document.controller
    post:
      security:
        - BearerAuth: []
      description: Создает документ
      operationId: createItem
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          description: Объект документа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
    get:
      security:
        - BearerAuth: []
      description: Отдает список документов
      operationId: getList
      parameters:
        - $ref: '#/components/parameters/TakeParam'
        - $ref: '#/components/parameters/SkipParam'
      responses:
        '200':
          description: Список документов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'

  /documents/{id}:
    x-exegesis-controller: document.controller
    get:
      security:
        - BearerAuth: []
      description: Отдаёт документ
      operationId: getItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      responses:
        '200':
          description: Объект документа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
    put:
      security:
        - BearerAuth: []
      description: Модифицирует документ
      operationId: updateItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          description: Модфицированный документ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
    delete:
      security:
        - BearerAuth: []
      description: Удаляет документ и возвращает его
      operationId: deleteItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      responses:
        '200':
          description: Удаленный документ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'

  /students:
    x-exegesis-controller: student.controller
    post:
      security:
        - BearerAuth: []
      description: Создает студента
      operationId: createItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Объект студента
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
    get:
      security:
        - BearerAuth: []
      description: Отдает список студентов
      operationId: getList
      parameters:
        - $ref: '#/components/parameters/TakeParam'
        - $ref: '#/components/parameters/SkipParam'
      responses:
        '200':
          description: Список студентов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'

  /students/{id}:
    x-exegesis-controller: student.controller
    get:
      security:
        - BearerAuth: []
      description: Отдаёт студента
      operationId: getItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      responses:
        '200':
          description: Объект студента
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
    put:
      security:
        - BearerAuth: []
      description: Модифицирует студента
      operationId: updateItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Модфицированный студент
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
    delete:
      security:
        - BearerAuth: []
      description: Удаляет студента и возвращает его
      operationId: deleteItem
      parameters:
        - $ref: '#/components/parameters/UidParam'
      responses:
        '200':
          description: Удаленный студент
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'

components:
  parameters:
    UidParam:
      name: id
      in: path
      schema:
        type: string
      required: true

    TakeParam:
      name: take
      in: path
      schema:
        type: integer
        minimum: 0
        maximum: 50
        default: 50

    SkipParam:
      name: skip
      in: path
      schema:
        type: integer
        minimum: 0
        maximum: 50
        default: 0

  responses:
     Unauthorized:
      description: Отстуствует авторизация / Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    User:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseSchema'
        - type: object
          properties:
            username:
              type: string
            password:
              type: string
            role:
              type: array
              items:
                type: string
              nullable: true
            accessToken:
              nullable: true
              type: string
            department:
              anyOf:
                - $ref: '#/components/schemas/EDepartment'
                - type: object
                  nullable: true
            leadsGroup:
              nullable: true
              type: array
              items:
                type: string
            personalData:
              anyOf:
                - type: object
                  nullable: true
                - $ref: '#/components/schemas/IPersonalData'
              
    Group:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseSchema'
        - type: object
          properties:
            name:
              type: string

    Specialization:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseSchema'
        - type: object
          properties:
            name:
              type: string

    Document:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseSchema'
        - type: object
          properties:
            canRead:
              nullable: true
              type: array
              items:
                type: string
            canEdit:
              nullable: true
              type: array
              items:
                type: string
            name:
              type: string
            department:
              nullable: true
              type: string
            type:
              nullable: true
              type: string
            data:
              type: string

    Student:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseSchema'
        - type: object
          properties:
            specialization:
              $ref: '#/components/schemas/Specialization'
            group:
              $ref: '#/components/schemas/Group'
            personalData:
              $ref: '#/components/schemas/IPersonalData'
            creditCard:
              type: string
              nullable: true

    BaseSchema:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

    IPersonalData:
      type: object
      properties:
        surname: 
          type: string
        name: 
          type: string
        patronymic: 
          type: string
        phone: 
          type: string
        SNILS: 
          type: string
        INN: 
          type: string
        email: 
          type: string
        residentialAddress: 
          type: object
          properties:
            real:
              type: string
            registration:
              type: string
        passport: 
          type: object
          properties:
            issuedAt:
              type: string
              format: date
            issuesPlace:
              type: string
            number:
              type: string
            series:
              type: string
            birthdate:
              type: string
              format: date

    EDepartment:
      type: string
      enum:
        - any
        - it

    ERoles:
      type: string
      enum:
        - all
        - admin
        - curator
        - educator
        - supervisor

    EDocType:
      type: string
      enum:
        - any
        - report
        - statement
