openapi: '3.0.2'
info:
  title: OpenAPI Foreduc
  version: '1.0'

paths:
  /users:
    x-exegesis-controller: user.controller
    # x-exegesis-roles: ['any']
    post:
      summary: Регистрация пользователя (только для админов)
      operationId: createAdmin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
    get:
      operationId: getList
      parameters:
        - in: query
          name: department
          required: false
          schema:
            $ref: '#/components/schemas/EDepartment'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        # '403':
        #   $ref: '#/components/responses/Unauthorized'

components:
  responses:
     Unauthorized:
      description: Отстуствует авторизация / Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    User:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseSchema'
        - type: object
          properties:
            username:
              type: string
            password:
              type: string
            role:
              type: string
            accessToken:
              type: string
            department:
              $ref: '#/components/schemas/EDepartment'
            leadsGroup:
              type: array
              items:
                type: string
            personalData:
              $ref: '#/components/schemas/IPersonalData'
              
    BaseSchema:
      type: object
      properties:
        _id:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

    IPersonalData:
      type: object
      properties:
        surname: 
          type: string
        name: 
          type: string
        patronymic: 
          type: string
        phone: 
          type: string
        SNILS: 
          type: string
        INN: 
          type: string
        email: 
          type: string
        residentialAddress: 
          type: object
          properties:
            real:
              type: string
            registration:
              type: string
        passport: 
          type: object
          properties:
            issuedAt:
              type: string
              format: date
            issuesPlace:
              type: string
            number:
              type: string
            series:
              type: string
            birthdate:
              type: string
              format: date

    EDepartment:
      type: string
      enum:
        - any
        - it

    ERoles:
      type: string
      enum:
        - all
        - admin
        - curator
        - educator
        - supervisor

    EDocType:
      type: string
      enum:
        - any
        - report
        - statement

    SkipParam:
      type: number
      nullable: true

    TakeParam:
      type: number
      nullable: true